# @package _global_

# overfits to 3 batches

defaults:
  - default.yaml

trainer:
  max_epochs: 2000
  overfit_batches: 3

# model ckpt and early stopping need to be disabled during overfitting
callbacks: null
